name: CI - Build Docker Image

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - uses: docker/login-action@v2.0.0
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - uses: docker/build-push-action@v3.0.0
      name: Build and Push Docker Image
      with:
        push: true
        tags: nicholassiew1991/sleekflow-todo-api:latest
